### ISSUE TITLE
PHP8.1 Support

### ISSUE THREAD

**Issue by BorisovskiP** [mediarox/module-checkout-placeholder#8]
Hello,
Are there any plans to add support for Magento 2.4.5 (PHP8.1)?

**Comment by sfritzsche** [comment]
Yes. We will prepare an update shortly.

**Comment by sfritzsche** [comment]
@BorisovskiP Can you try 0.4.3 pls ? Fast changed it right now.

**Comment by BorisovskiP** [comment]
@sfritzsche that works fine now, thanks. Mind also updating https://github.com/mediarox/module-checkout-street-number ?

**Comment by sfritzsche** [comment]
@BorisovskiP Done.)

**Comment by BorisovskiP** [comment]
@sfritzsche Thanks.
